name: github-bump-version-release
description: Buildkite plugin that bump version and release it to GitHub
author: https://github.com/dx-oss
requirements: []
configuration:
  pattern:
    name: string
    ver: string
  additionalProperties: false
