name: "github-bump-version-release"
description: Buildkite plugin that bump version and release it to GitHub
author: https://github.com/dx-oss
requirements: ["docker","buildkite-agent","github-release"]
configuration:
  key:
    name: string
    description: Fetch another key from SemVer from GitVersion
  image:
    name: string
    description: Docker image use to fetch GitVersion (dxdx/docker-builder-dotnet:2.2)
  debug:
    name: int
    description: if value is greater then zero the plugin will expose debug information
  dry:
    name: int
    description: if value is greater then zero the plugin will not pusht the new release
  docker:
    name: string
    description: docker binary
  agent:
    name: string
    description: buildkite-agent binary (https://github.com/buildkite/agent)
  # release:
  #   name: string
  #   description: gitub-release binary (https://github.com/github-release/github-release)
  additionalProperties: false
