#!/bin/bash

ssh-keyscan github.com > ~/.ssh/known_hosts

branch=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_BRANCH:-master}
branch=${BUILDKITE_PIPELINE_DEFAULT_BRANCH:-$branch}

pwd=$(pwd)
cd
rm -rf ${BUILDKITE_BUILD_CHECKOUT_PATH}

echo "clone ${BUILDKITE_REPO} ${BUILDKITE_BUILD_CHECKOUT_PATH}"
git clone ${BUILDKITE_REPO} ${BUILDKITE_BUILD_CHECKOUT_PATH}
cd $pwd

git checkout $branch
echo "Checkout $branch"
