#!/bin/bash

# https://buildkite.com/docs/pipelines/writing-build-scripts
set -euo pipefail

# common

dotnet=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_DOTNET:-dotnet}
#github_release=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_RELEASE:-github-release}
buildkite_agent=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_AGENT:-buildkite-agent}

image="dxdx/docker-builder-dotnet:2.2"
image=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_IMAGE:-$image}

debug=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_DEBUG:-0}
if [ $debug -gt 0 ]; then
    env
    docker version
    docker ps    
    whoami
    pwd
fi

docker=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_DOCKER:-docker}

# version

version="v0.0.0"
dotnet_args="--rm -it $image /gitversion/GitVersion.dll /output json /nofetch /showvariable semVer"
version=$($docker run -v $(pwd):/src -w /src --entrypoint dotnet $dotnet_args)

if [ "$version" = "" ]; then
    $buildkite_agent annotate --style error "Cannot get any version"

    exit 1    
else
    $buildkite_agent meta-data set version $version
    $buildkite_agent annotate --style info "Using [$image] with GitVersion and SemVer"
    $buildkite_agent annotate --style success "Bump to version ${version}"

    export VERSION=$version

    echo $version
fi

# release

if [ "$GITHUB_TOKEN" = "" ]; then
    echo "GITHUB_TOKEN token is not set"

    $buildkite_agent annotate --style error "Cannot release version ${version} with GITHUB_TOKEN is not set"

    exit 1
fi

export GITHUB_USER=$(echo "git@github.com:dxcn/oxy-dotnet-foundation.git" | cut -d: -f 2 | cut -d/ -f 1)
export GITHUB_REPO=$(echo "$BUILDKITE_REPO" | cut -d: -f 2 | cut -d/ -f 2 | cut -d. -f 1)

# TODO: use https://github.com/github-release/github-release instead when it support default github description behaviour
echo '{"tag_name": "VERSION","name": "VERSION","draft": false,"prerelease": false}' > payload.json
sed -s "s/VERSION/$version/gi" -i payload.json
curl -f -q -H "Authorization: token $GITHUB_TOKEN" --data @payload.json https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/releases
rm payload.json
$buildkite_agent annotate --style success "Push release ${version}"
